export const IMG_URL="https://www.tanntrim.com/_next/image?url=https%3A%2F%2Ftann.gumlet.io%2Fmedia%2Fgen%2Fimage%2FSIPR04031_01_rnZiBfp.JPG&w=384&q=75"

export const jsonData = [
  {
    id: 1,
    image: "assets/image1.jpg",
    title: "The Brown Metro Movers",
    cost: 4899,
    lastPrice: 8999,
    offer: "50%",
  },
  {
    id: 2,
    image: "assets/image2.jpg",
    title: "The Brown Metro Movers",
    cost: 4899,
    lastPrice: 8999,
    offer: "50%",
  },
  {
    id: 3,
    image: "assets/image3.jpg",
    title: "The Brown Metro Movers",
    cost: 4899,
    lastPrice: 8999,
    offer: "50%",
  },
  {
    id: 4,
    image: "assets/image4.jpg",
    title: "The Brown Metro Movers",
    cost: 4899,
    lastPrice: 8999,
    offer: "50%",
  },
  {
    id: 5,
    image: "assets/image5.jpg",
    title: "The Brown Metro Movers",
    cost: 4899,
    lastPrice: 8999,
    offer: "50%",
  },
  {
    id: 6,
    image: "assets/image6.jpg",
    title: "The Brown Metro Movers",
    cost: 4899,
    lastPrice: 8999,
    offer: "50%",
  },
  {
    id: 7,
    image: "assets/image7.jpg",
    title: "The Brown Metro Movers",
    cost: 4899,
    lastPrice: 8999,
    offer: "50%",
  },
  {
    id: 8,
    image: "assets/image8.jpg",
    title: "The Brown Metro Movers",
    cost: 4899,
    lastPrice: 8999,
    offer: "50%",
  },
  {
    id: 9,
    image: "assets/image9.jpg",
    title: "The Brown Metro Movers",
    cost: 4899,
    lastPrice: 8999,
    offer: "50%",
  },
  {
    id: 10,
    image: "assets/image10.jpg",
    title: "The Brown Metro Movers",
    cost: 4899,
    lastPrice: 8999,
    offer: "50%",
  },
  {
    id: 11,
    image: "assets/image11.jpg",
    title: "The Brown Metro Movers",
    cost: 4899,
    lastPrice: 8999,
    offer: "50%",
  },
  {
    id: 12,
    image: "assets/image12.jpg",
    title: "The Brown Metro Movers",
    cost: 4899,
    lastPrice: 8999,
    offer: "50%",
  },
];
